application: google.com:ls
version: 8
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /admin/.*
  script: google.appengine.ext.admin.application
- url: .*
  script: main.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

builtins:
- appstats: on
inbound_services:
- warmup
